### ISSUE TITLE
initialState is confusing

### ISSUE THREAD

**Issue by bookercodes** [25th-floor/revalidation#34]
I still need to wrap my head around why it's needed. If you forget to specify it, there are no obvious errors but weird things happen (`validateAll` doesn't work and you get a controlled component error when you type)

Just adding this as a mental note so we can address it in the documentation :)

**Comment by busypeoples** [comment]
We don't know anything about the form and its elements. So somehow we need to get hold of the initial model. otherwise React will complain because we would be switching from uncontrolled to controlled components. So the initial state has to be declared somewhere. We can also initialize the errors  due to the fact that we know of the initial form values.

**Comment by busypeoples** [comment]
User land could define a fallback when accessing a non defined value like so: `<input value={form.foo || ''} />` but I would rather avoid this.
